version: '3.6'

services:
  app:
    image: ${DOCKER_REGISTRY}/app:${BRANCH}.${VERSION}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CONFIGURATION: "${CONFIGURATION:-Release}"      
    environment:
      RUN_TEST: ${RUN_TEST:-false}