version: '3.5'

services:
  sistema-cnj-jus-br:
    build:
      target: build
    environment:
      AUTH_AUTHORITY: 'http://localhost:8080/auth/realms/master/'
      AUTH_CLIENT_ID: 'http://localhost:4200'
      AUTH_SCOPE: 'openid profile email roles offline_access'
    ports:
      - 4200:4200