version: '3.6'

services:
  sistema-cnj-jus-br:
    image: ${DOCKER_REGISTRY}dsa/sistema.cnj.jus.br:${BRANCH:-develop}.${VERSION:-local}
    container_name: sistema.cnj.jus.br-local
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_HREF: /
