version: '3.5'

services:
  app-front-end:
    image: ${DOCKER_REGISTRY}dsa/sistema.cnj.jus.br:${BRANCH}.${VERSION}
    ports:
      - "80:80"    
    environment:
      AUTH_AUTHORITY: 'https://sso-alpha.cnj.jus.br/auth/realms/master/'
      AUTH_CLIENT_ID: 'sistema-${BRANCH:-develop}-alpha.cnj.jus.br'
      AUTH_SCOPE: 'openid profile email roles offline_access'
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
        reservations:
          cpus: '0.1'
          memory: 128M
    labels:
      kompose.service.expose: sistema-rc.cnj.jus.br

networks:
  default:
    name: ns-sistema-rc
