version: '3.5'

services:
  sistema-cnj-jus-br:
    image: ${DOCKER_REGISTRY}dsa/sistema.cnj.jus.br:${BRANCH}.${VERSION}
    environment:
      AUTH_AUTHORITY: 'https://sso.cnj.jus.br/auth/realms/master/'
      AUTH_CLIENT_ID: 'sistema.cnj.jus.br'
      AUTH_SCOPE: 'openid profile email roles offline_access'
    ports:
      - "80:80"
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.20'
          memory: 3072M
        reservations:
          cpus: '0.01'
          memory: 1M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 120s
    labels:
      kompose.service.expose: sistema.cnj.jus.br

networks:
  default:
    name: ns-sistema
