version: '3.5'

services:
  app:
    image: ${DOCKER_REGISTRY}/app:${BRANCH}.${VERSION}
    environment:
      RUN_TEST: ${RUN_TEST:-false}
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "80:80"       
      - "443:443"      
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
        reservations:
          cpus: '0.1'
          memory: 128M    
    labels:
      kompose.service.expose: app-${BRANCH}-dev        

networks:
  default:
    name: ns-app-${BRANCH}-dev