version: "3.5"

services:
  sistema-cnj-jus-br:
    image: ${DOCKER_REGISTRY}sistema.cnj.jus.br:${BRANCH}.${VERSION}-debug
    environment:
      AUTH_AUTHORITY: 'https://sso-alpha.cnj.jus.br/auth/realms/master/'
      AUTH_CLIENT_ID: 'sistema-${BRANCH_DNS:-develop}-alpha.cnj.jus.br'
      AUTH_SCOPE: 'openid profile email roles offline_access'
    ports:
      - "80:4200"
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.20'
          memory: 3072M
        reservations:
          cpus: '0.01'
          memory: 1M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 120s
    labels:
      kompose.service.expose: sistema-${BRANCH_DNS}-alpha.cnj.jus.br

networks:
  default:
    name: ns-sistema-${BRANCH_DNS}-alpha